

python:
  - "3.6.1"
cache: pip
# command to install dependencies
install:
  
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install nose
  - pip install coverage
# command to run the app
script:
  - nosetests --with-coverage tests
  
after_success:
  - coveralls